### ISSUE TITLE
Feature Request: Include county data in extraction 

### ISSUE THREAD

**Issue by jonekeat** [nacnudus/google-location-coronavirus#3]
Hi @nacnudus 

Thanks for your contribution by providing the Google mobility time series.

Just a suggestion, Is it possible to include US county data by extracting US states report? eg. `https://www.gstatic.com/covid19/mobility/2020-03-29_US_Alabama_Mobility_Report_en.pdf`

I saw in your `extract.R`
``` r
#' Extract URLs from home page
extract_urls <- function(url) {
  url %>%
    read_html() %>%
    html_nodes(".country-data a") %>%
    html_attr("href") %>%
    tibble(url = .) %>%
    mutate(file_path = path("pdf", basename(url)))
}
```   
maybe we can include those `class attr = region-data` by specify `".country-data a, .region-data a"` in html_nodes? like
``` r
#' Extract URLs from home page
extract_urls <- function(url) {
  url %>%
    read_html() %>%
    html_nodes(".country-data a, .region-data a") %>%
    html_attr("href") %>%
    tibble(url = .) %>%
    mutate(file_path = path("pdf", basename(url)))
}
```

**Comment by nacnudus** [comment]
Yes! https://github.com/nacnudus/google-location-coronavirus/blob/master/2020-03-29-region.tsv
