### ISSUE TITLE
South Korea, Retail and Recreation data missing

### ISSUE THREAD

**Issue by sabrown1016** [nacnudus/google-location-coronavirus#6]
Hi, South Korea's country level data for the "Retail and Recreation" category is missing (in the 2020-04-11-country.tsv file) and incomplete in the  master/country.zip file (it only includes data up to 04/05/2020). Hopefully this is an easy fix.

**Comment by nacnudus** [comment]
Thanks, it turned out to be a simple change to the position of some text.  Please note that Google now publishes its own CSV files.  https://www.google.com/covid19/mobility/
